/sentry/marker_detector_node:
  ros__parameters:
    armor_detector:
      armor_type_threshold: 3.6
      bin3_threshold_1: 40.0
      bin3_threshold_2: 10.0
      bin3_threshold_3: 0.1
      binary_method: 3
      ch1_max_b: 255.0
      ch1_max_r: 255.0
      ch1_min_b: 100.0
      ch1_min_r: 0.0
      ch2_max: 255.0
      ch2_min: 0.0
      ch3_max_b: 255.0
      ch3_max_r: 255.0
      ch3_min_b: 0.0
      ch3_min_r: 100.0
      contours_length1_max: 300.0
      contours_length1_min: 7.0
      exp_time: 3200
      gray_threshold: 40.0
      height: 540
      is3big: false
      is4big: false
      is5big: false
      is_number: true
      led_diff: 0.3
      led_height_max: 100.0
      led_height_min: 5.0
      led_ratio_max: 20.0
      led_ratio_min: 1.0
      led_vertical_angle: 60.0
      marker_direction_angle: 30.0
      marker_parallel_angle: 30.0
      marker_ratio_max: 6.0
      marker_ratio_min: 0.8
      marker_size_max: 2000.0
      marker_size_min: 1.0
      offset_h: 256
      offset_w: 0
      width: 720
    buff_detector:
      analysis_points_num: 150
      delay_time: 0.35
      exp_time: 1750
      height: 500
      offset_H: 162
      offset_W: 290
      width: 500
    if_get_angle: true
    is_red: false
    qos_overrides:
      /parameter_events:
        publisher:
          depth: 1000
          durability: volatile
          history: keep_last
          reliability: reliable
    show: true
    use_sim_time: false

