/marker_tracker_node:
  ros__parameters:
    ballistics:
      fire_delay: 0
    camera:
      height_offset: 0.0
      pitch_offset: 2.0
      x_offset: 0.0
      yaw_offset: -0.4
      z_offset: 0.0
    kalman:
      Dt: 0.005
      Q_R: 1.0e-06
      Q_theta: 0.01
      Q_w: 0.01
      Q_x: 0.0
      Q_x0: 1.0e-05
      Q_y: 0.0
      Q_y0: 1.0e-05
      Q_z: 0.01
      Qa_a: 1.0e-07
      Qa_ang: 0.0001
      Qa_gain: 0.1
      Qa_theta: 0.0
      Qa_v: 0.0
      Qa_w: 1.0e-07
      Qx_gain: 120.0
      R_theta: 0.01
      R_x: 0.002
      R_y: 0.002
      R_z: 0.0001
      Ra_ang: 0.01
      Ra_gain: 0.01
      Rx_gain: 0.0009
    qos_overrides:
      /parameter_events:
        publisher:
          depth: 1000
          durability: volatile
          history: keep_last
          reliability: reliable
    use_sim_time: false

